"""
Crypto Payments Integration
Accept Bitcoin, Ethereum, and other cryptocurrencies
Feature #3 of 35
"""
import os
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Dict, Any
from datetime import datetime, timezone
from uuid import uuid4
from config import get_database

router = APIRouter(prefix="/crypto-payments", tags=["crypto"])

# GlobalVibe DSG Solana receive wallet (configured in backend/.env).
# This is the on-chain address that incoming SOL / SPL deposits should be sent to.
GLOBAL_VIBEZ_SOLANA_RECEIVE_WALLET = os.environ.get(
    "GLOBAL_VIBEZ_SOLANA_RECEIVE_WALLET", ""
).strip()

# Supported cryptocurrencies
SUPPORTED_CRYPTO = {
    "BTC": {"name": "Bitcoin", "network": "bitcoin", "decimals": 8},
    "ETH": {"name": "Ethereum", "network": "ethereum", "decimals": 18},
    "USDT": {"name": "Tether", "network": "ethereum", "decimals": 6},
    "USDC": {"name": "USD Coin", "network": "ethereum", "decimals": 6},
    "SOL": {"name": "Solana", "network": "solana", "decimals": 9}
}

# Networks for which the GlobalVibe Solana receive wallet is valid.
# (SOL native + any SPL token on Solana — e.g. USDC-SPL would also land here.)
SOLANA_NETWORKS = {"solana"}

class CryptoDepositRequest(BaseModel):
    user_id: str
    cryptocurrency: str  # BTC, ETH, USDT, etc.
    amount_usd: float

class CryptoWithdrawalRequest(BaseModel):
    user_id: str
    cryptocurrency: str
    wallet_address: str
    amount_usd: float

@router.get("/supported-currencies")
async def get_supported_currencies() -> Dict[str, Any]:
    """Get list of supported cryptocurrencies"""
    return {
        "success": True,
        "currencies": SUPPORTED_CRYPTO
    }

@router.get("/platform-receive-wallet")
async def get_platform_receive_wallet() -> Dict[str, Any]:
    """
    Return the GlobalVibe DSG Solana receive wallet so the frontend can
    display a deposit address / QR for users sending SOL or SPL tokens.
    """
    if not GLOBAL_VIBEZ_SOLANA_RECEIVE_WALLET:
        raise HTTPException(
            status_code=503,
            detail="Platform Solana receive wallet is not configured."
        )
    return {
        "success": True,
        "network": "solana",
        "address": GLOBAL_VIBEZ_SOLANA_RECEIVE_WALLET,
        "label": "GlobalVibe DSG Treasury",
    }

@router.post("/create-deposit")
async def create_crypto_deposit(request: CryptoDepositRequest) -> Dict[str, Any]:
    """
    Create a crypto deposit for a user.

    For Solana-network coins (SOL + SPL), we return the GlobalVibe DSG receive
    wallet from .env plus a unique per-deposit `memo` so the on-chain transfer
    can be matched back to the user when the indexer confirms it.
    """
    db = get_database()

    crypto = SUPPORTED_CRYPTO.get(request.cryptocurrency)
    if not crypto:
        raise HTTPException(status_code=400, detail="Cryptocurrency not supported")

    deposit_id = str(uuid4())

    if crypto["network"] in SOLANA_NETWORKS:
        if not GLOBAL_VIBEZ_SOLANA_RECEIVE_WALLET:
            raise HTTPException(
                status_code=503,
                detail="Solana receive wallet is not configured on the platform."
            )
        deposit_address = GLOBAL_VIBEZ_SOLANA_RECEIVE_WALLET
        # Short, memo-friendly tag for matching the tx back to this deposit row.
        memo = f"GVZ-{deposit_id[:8]}"
    else:
        # Other networks (BTC / ETH / ERC-20) still need a per-user address
        # generated by an external processor (Coinbase Commerce / BitPay / etc).
        deposit_address = f"GENERATED_ADDRESS_{uuid4().hex[:16]}"
        memo = None

    deposit = {
        "deposit_id": deposit_id,
        "user_id": request.user_id,
        "cryptocurrency": request.cryptocurrency,
        "network": crypto["network"],
        "amount_usd": request.amount_usd,
        "status": "pending",
        "deposit_address": deposit_address,
        "memo": memo,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "expires_at": (datetime.now(timezone.utc).timestamp() + 3600)  # 1 hour expiry
    }

    await db.crypto_deposits.insert_one(deposit)
    deposit.pop("_id", None)

    return {
        "success": True,
        "deposit": deposit,
        "message": (
            f"Send {request.cryptocurrency} to the address above"
            + (f" with memo `{memo}` so we can credit your account." if memo else ".")
        )
    }

@router.post("/withdraw")
async def crypto_withdrawal(request: CryptoWithdrawalRequest) -> Dict[str, Any]:
    """Process crypto withdrawal"""
    db = get_database()
    
    user = await db.users.find_one({"user_id": request.user_id}, {"_id": 0})
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    
    if user.get("balance", 0) < request.amount_usd:
        raise HTTPException(status_code=400, detail="Insufficient balance")
    
    # Create withdrawal
    withdrawal = {
        "withdrawal_id": str(uuid4()),
        "user_id": request.user_id,
        "cryptocurrency": request.cryptocurrency,
        "wallet_address": request.wallet_address,
        "amount_usd": request.amount_usd,
        "status": "pending",
        "created_at": datetime.now(timezone.utc).isoformat()
    }
    
    await db.crypto_withdrawals.insert_one(withdrawal)
    
    # Deduct balance
    await db.users.update_one(
        {"user_id": request.user_id},
        {"$inc": {"balance": -request.amount_usd}}
    )
    
    return {
        "success": True,
        "withdrawal": withdrawal,
        "message": "Withdrawal request submitted for processing"
    }

@router.get("/deposit-status/{deposit_id}")
async def get_deposit_status(deposit_id: str) -> Dict[str, Any]:
    """Check status of crypto deposit"""
    db = get_database()
    
    deposit = await db.crypto_deposits.find_one({"deposit_id": deposit_id}, {"_id": 0})
    if not deposit:
        raise HTTPException(status_code=404, detail="Deposit not found")
    
    return {"success": True, "deposit": deposit}

@router.get("/transaction-history/{user_id}")
async def get_crypto_history(user_id: str) -> Dict[str, Any]:
    """Get user's crypto transaction history"""
    db = get_database()
    
    deposits = await db.crypto_deposits.find({"user_id": user_id}, {"_id": 0}).sort("created_at", -1).to_list(100)
    withdrawals = await db.crypto_withdrawals.find({"user_id": user_id}, {"_id": 0}).sort("created_at", -1).to_list(100)
    
    return {
        "success": True,
        "deposits": deposits,
        "withdrawals": withdrawals
    }
