import { useLocation } from "react-router-dom";

/** Routes that own the entire viewport (h-[100dvh] + overflow-hidden).
 *  Global chrome bars and the mobile bottom nav should not mount on
 *  these pages so game CTAs stay reachable. */
export const FULLSCREEN_GAME_ROUTES = [
  "/spades",
  "/bid-whist",
  "/hearts",
  "/uno",
  "/euchre",
  "/pinochle",
  "/gin-rummy",
  "/rummy",
  "/war",
  "/crazy-eights",
  "/go-fish",
  "/dominoes",
  "/dominoes-mp",
  "/baccarat",
  "/baccarat-aaa",
  "/baccarat-premium",
  "/blackjack",
  "/blackjack-universal",
  "/poker",
  "/poker-practice",
  "/three-card-poker",
  "/vibe-654",
  "/vibez-654",
  "/games/vibez-654",
  "/games/vibe654",
  "/dice",
  "/chess",
  "/checkers",
  "/connect4",
  "/practice/play",
  "/chess-hall",
  "/chess/blitz",
  "/chess/puzzle",
  "/chess/tournament",
  "/chess/multiplayer",
  "/sports-lounge",
  "/sportsbook",
  "/card-mp",
  "/cinema-room",
  "/cyber-casino",
  "/games/cyber-casino",
  "/casino/high-roller",
  "/high-roller",
  "/multiplayer-poker",
  "/multiplayer-blackjack",
  "/multiplayer-slots",
  "/community-slots",
  "/vibes-slots",
  "/european-roulette",
  "/sic-bo",
  "/craps",
  "/keno",
  "/bingo",
  "/caribbean-stud",
  "/http-multiplayer-game",
  "/game",
  "/casino-war",
  "/lottery",
  "/dsg6",
  "/underground-casino",
  "/underground",
];

export default function useIsFullscreenGameRoute(): boolean {
  const location = useLocation();
  const p = location.pathname;
  return FULLSCREEN_GAME_ROUTES.some((r) => p === r || p.startsWith(r + "/"));
}
