/**
 * DirectUpload — reusable in-app uploader replacing every "paste a URL"
 * field. Spec source: Direct_Upload_Implementation_Guide.pdf
 *
 *   • One "Upload Media" button (no URL input)
 *   • Native file picker opens camera on mobile via `capture` attr
 *   • Multi-format: images (jpg/png/webp/gif), videos (mp4/mov/webm), PDF
 *   • Visual progress bar during upload
 *   • Thumbnail preview after success (image inline, video preview tag,
 *     PDF: filename + icon)
 *   • Hidden URL handling — caller just gets the resolved URL via onChange
 *
 * Usage:
 *   <DirectUpload kind="cover" value={url} onChange={setUrl} accept="image" />
 */
import React, { useRef, useState } from "react";
import { Upload, X, Image as ImageIcon, Video, FileText, Loader2, Camera, Sparkles } from "lucide-react";
import { toast } from "sonner";

const API = process.env.REACT_APP_BACKEND_URL!;

type Kind =
  | "cover"
  | "walkthrough"
  | "commercial"
  | "dish_sizzle"
  | "atmosphere_loop"
  | "menu_pdf"
  | "generic";

type AcceptGroup = "image" | "video" | "pdf" | "image+video" | "all";

const ACCEPT_MAP: Record<AcceptGroup, string> = {
  image: "image/jpeg,image/png,image/webp,image/gif",
  video: "video/mp4,video/quicktime,video/webm",
  pdf: "application/pdf",
  "image+video": "image/jpeg,image/png,image/webp,image/gif,video/mp4,video/quicktime,video/webm",
  all: "image/jpeg,image/png,image/webp,image/gif,video/mp4,video/quicktime,video/webm,application/pdf",
};

export const DirectUpload: React.FC<{
  kind: Kind;
  value?: string;
  onChange: (url: string) => void;
  /**
   * Optional second callback fired with the auto-extracted thumbnail
   * URL after a video upload completes. Lets a parent form fill its
   * cover-photo field automatically without a second upload step.
   */
  onThumbnail?: (thumbUrl: string) => void;
  accept?: AcceptGroup;
  label?: string;
  cameraCapture?: boolean;        // mobile: opens camera directly
  /**
   * If the current value was auto-extracted from a video, set this true.
   * Renders an "Auto-generated · click to upload your own" overlay
   * nudging hosts/artisans to drop a hero shot.
   */
  isAutoGenerated?: boolean;
  testid?: string;
}> = ({ kind, value, onChange, onThumbnail, accept = "all", label, cameraCapture, isAutoGenerated, testid }) => {
  const inputRef = useRef<HTMLInputElement>(null);
  const [pct, setPct] = useState<number | null>(null);
  const [uploading, setUploading] = useState(false);

  const upload = async (file: File) => {
    setUploading(true);
    setPct(0);
    try {
      const fd = new FormData();
      fd.append("file", file);
      // XHR so we get progress events (fetch doesn't expose them)
      const result = await new Promise<{ file_url: string; thumbnail_url?: string | null }>(
        (resolve, reject) => {
          const xhr = new XMLHttpRequest();
          xhr.open("POST", `${API}/api/uploads/media?kind=${kind}`);
          xhr.withCredentials = true;
          xhr.upload.onprogress = (ev) => {
            if (ev.lengthComputable) {
              setPct(Math.round((ev.loaded / ev.total) * 100));
            }
          };
          xhr.onload = () => {
            if (xhr.status >= 200 && xhr.status < 300) {
              try {
                resolve(JSON.parse(xhr.responseText));
              } catch (e) {
                reject(new Error("Bad response"));
              }
            } else {
              try {
                const r = JSON.parse(xhr.responseText);
                reject(new Error(r.detail || `HTTP ${xhr.status}`));
              } catch {
                reject(new Error(`HTTP ${xhr.status}`));
              }
            }
          };
          xhr.onerror = () => reject(new Error("Network error"));
          xhr.send(fd);
        },
      );
      onChange(result.file_url);
      if (result.thumbnail_url && onThumbnail) {
        onThumbnail(result.thumbnail_url);
      }
      toast.success("Uploaded");
    } catch (e: any) {
      toast.error(e.message || "Upload failed");
    } finally {
      setUploading(false);
      setPct(null);
      if (inputRef.current) inputRef.current.value = "";
    }
  };

  const onPick = (e: React.ChangeEvent<HTMLInputElement>) => {
    const f = e.target.files?.[0];
    if (f) upload(f);
  };

  const clear = () => onChange("");

  // Render preview when we have a value
  const isImage = !!value && /\.(jpe?g|png|webp|gif)(\?|$)/i.test(value);
  const isVideo = !!value && /\.(mp4|mov|webm)(\?|$)/i.test(value);
  const isPdf = !!value && /\.pdf(\?|$)/i.test(value);
  const fullUrl = value && value.startsWith("/") ? `${API}${value}` : value;

  return (
    <div className="w-full" data-testid={testid}>
      {label && (
        <label className="block text-xs font-mono uppercase tracking-widest text-purple-300/80 mb-2">
          {label}
        </label>
      )}

      <input
        ref={inputRef}
        type="file"
        accept={ACCEPT_MAP[accept]}
        {...(cameraCapture ? { capture: "environment" as any } : {})}
        onChange={onPick}
        className="hidden"
        data-testid={`${testid || "direct-upload"}-input`}
      />

      {value && !uploading ? (
        <div className="relative rounded-lg overflow-hidden border border-fuchsia-500/30 bg-[#0B0618]">
          {isImage && (
            <img
              src={fullUrl}
              alt="upload"
              className="w-full max-h-56 object-cover"
              data-testid={`${testid || "direct-upload"}-preview-img`}
            />
          )}
          {isVideo && (
            <video
              src={fullUrl}
              controls
              muted
              className="w-full max-h-56 bg-black"
              data-testid={`${testid || "direct-upload"}-preview-video`}
            />
          )}
          {isPdf && (
            <div className="flex items-center gap-3 p-4">
              <FileText className="w-8 h-8 text-fuchsia-300" />
              <a
                href={fullUrl}
                target="_blank"
                rel="noreferrer"
                className="text-sm text-fuchsia-200 hover:underline truncate flex-1"
              >
                {value.split("/").pop()}
              </a>
            </div>
          )}
          {isAutoGenerated && isImage && (
            <button
              type="button"
              onClick={() => inputRef.current?.click()}
              className="absolute top-2 left-2 px-2.5 py-1 rounded-full bg-black/70 backdrop-blur border border-cyan-500/40 text-cyan-300 text-[10px] font-bold uppercase tracking-widest flex items-center gap-1.5 hover:bg-black/90 transition-colors"
              data-testid={`${testid || "direct-upload"}-auto-gen-badge`}
            >
              <Sparkles className="w-3 h-3" />
              Auto-generated · click to upload your own
            </button>
          )}
          <div className="flex gap-2 p-2 border-t border-fuchsia-500/20 bg-[#0F0720]">
            <button
              type="button"
              onClick={() => inputRef.current?.click()}
              className="text-xs px-3 py-1 rounded-full bg-fuchsia-500/10 border border-fuchsia-500/30 text-fuchsia-200 hover:bg-fuchsia-500/20 flex items-center gap-1.5"
              data-testid={`${testid || "direct-upload"}-replace-btn`}
            >
              <Upload className="w-3 h-3" /> Replace
            </button>
            <button
              type="button"
              onClick={clear}
              className="text-xs px-3 py-1 rounded-full border border-red-500/30 text-red-300 hover:bg-red-500/10 flex items-center gap-1.5"
              data-testid={`${testid || "direct-upload"}-clear-btn`}
            >
              <X className="w-3 h-3" /> Clear
            </button>
          </div>
        </div>
      ) : uploading ? (
        <div className="rounded-lg border border-fuchsia-500/30 bg-[#0B0618] p-6 text-center">
          <Loader2 className="w-8 h-8 mx-auto animate-spin text-fuchsia-300 mb-3" />
          <p className="text-sm text-fuchsia-200 mb-2">
            Uploading{pct != null ? ` · ${pct}%` : "…"}
          </p>
          <div className="w-full h-2 bg-[#1A0D2E] rounded-full overflow-hidden">
            <div
              className="h-full bg-gradient-to-r from-fuchsia-500 to-purple-600 transition-all"
              style={{ width: `${pct ?? 0}%` }}
              data-testid={`${testid || "direct-upload"}-progress`}
            />
          </div>
        </div>
      ) : (
        <button
          type="button"
          onClick={() => inputRef.current?.click()}
          className="w-full p-6 rounded-lg border-2 border-dashed border-fuchsia-500/30 hover:border-fuchsia-400/60 bg-[#0B0618] hover:bg-fuchsia-500/5 transition-all flex flex-col items-center justify-center gap-2 group"
          data-testid={`${testid || "direct-upload"}-trigger-btn`}
        >
          <div className="flex items-center gap-3">
            {accept === "image" && <ImageIcon className="w-5 h-5 text-fuchsia-300" />}
            {accept === "video" && <Video className="w-5 h-5 text-fuchsia-300" />}
            {accept === "pdf" && <FileText className="w-5 h-5 text-fuchsia-300" />}
            {(accept === "image+video" || accept === "all") && (
              <Upload className="w-5 h-5 text-fuchsia-300" />
            )}
            <span className="text-sm font-bold text-fuchsia-100">Upload Media</span>
            {cameraCapture && (
              <span className="flex items-center gap-1 text-xs text-cyan-300">
                <Camera className="w-3 h-3" /> camera ok
              </span>
            )}
          </div>
          <p className="text-[11px] text-purple-300/60 leading-relaxed text-center max-w-xs">
            {accept === "image" && "JPG · PNG · WEBP · GIF (max 10 MB)"}
            {accept === "video" && "MP4 · MOV · WEBM (max 100 MB)"}
            {accept === "pdf" && "PDF (max 25 MB)"}
            {accept === "image+video" && "Images (10 MB) · Videos MP4/MOV/WEBM (100 MB)"}
            {accept === "all" && "Image · Video · PDF · Stays inside the app"}
          </p>
        </button>
      )}
    </div>
  );
};

export default DirectUpload;
